# Generated by Django 6.0 on 2025-12-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postcomment_post_alter_postview_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
